name: Backend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'src-backend/**'
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Configure poetry
      run: |
        poetry config virtualenvs.create true
        poetry config virtualenvs.in-project true

    - name: Cache poetry dependencies
      uses: actions/cache@v3
      with:
        path: src-backend/.venv
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Install dependencies
      run: |
        cd src-backend
        poetry install

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          # 停止现有服务
          pm2 stop wordbook-backend || true
          
          # 清理并创建目录
          rm -rf /var/www/wordbook/backend
          mkdir -p /var/www/wordbook/backend
          
          # 复制新代码
          cd /var/www/wordbook/backend
          git clone https://github.com/${{ github.repository }} .
          cd src-backend
          
          # 安装 poetry（如果需要）
          if ! command -v poetry &> /dev/null; then
            curl -sSL https://install.python-poetry.org | python3 -
          fi
          
          # 安装依赖
          poetry install --no-dev
          
          # 启动服务
          pm2 start "poetry run uvicorn main:app --host 0.0.0.0 --port 8000" --name wordbook-backend 